package com.apibridge.apibridge.model;

public enum ChangeType {
    ENDPOINT_REMOVED,
    METHOD_REMOVED,
    PARAMETER_REMOVED,
    PARAMETER_REQUIRED_ADDED,
    PARAMETER_TYPE_CHANGED,
    REQUEST_BODY_REMOVED,
    REQUEST_BODY_REQUIRED_ADDED,
    REQUEST_FIELD_REMOVED,
    REQUEST_FIELD_REQUIRED_ADDED,
    REQUEST_FIELD_TYPE_CHANGED,
    RESPONSE_REMOVED,
    RESPONSE_FIELD_REMOVED,
    RESPONSE_FIELD_TYPE_CHANGED
}
